### ISSUE TITLE
Where are the Italic sources

### ISSUE THREAD

**Issue by m4rc1e** [andrew-paglinawan/QuicksandFamily#3]
2.1 is lacking Italic sources. Is this intentional. The ReadMe states **- Added true italics for each weight**

Old release on GF features Italics.

Cheers,
Marc

**Comment by m4rc1e** [comment]
ping @ThomasJockin

**Comment by ThomasJockin** [comment]
Quicksand 1.0 did not have italics. Quicksand 2.0 introduced italics.

**Comment by m4rc1e** [comment]
Yeah but the latest folder in sources, 2.1. Has no Italic .glyphs file.

**Comment by ThomasJockin** [comment]
Correct. I was not able to apply improvements to italics. Only had time for Romans.

**Comment by m4rc1e** [comment]
Ok, I'll steal the Italic 2.0 files ;)
