### ISSUE TITLE
Italic sources in v2.0/2.1 are not compatible

### ISSUE THREAD

**Issue by m4rc1e** [andrew-paglinawan/QuicksandFamily#4]
Hey folks,

I'm not aware of the brief but we have 4 weights in the Roman, Light, Regular, Medium and Bold. 

In the v2.0 folder we had 3 seperate .glyphs files for Light Italic, Regular Italic and Bold Italic. I combined them and they're not compatible, hence why Medium is screwed.

![screen shot 2016-09-30 at 11 52 44](https://cloud.githubusercontent.com/assets/7525512/18987958/a997708a-8704-11e6-9b14-69f6fc984258.png)

Are we releasing the Italics as 3 weights or do we need 4 weights. Sorry I expected this to be in better condition or maybe I'm missing something?

@ThomasJockin @davelab6

Cheers,
Marc

**Comment by ThomasJockin** [comment]
Considering the italics will not have the character set support to match the Romans plus the interpolation issues with the new weight, my view is not to release the italics in this round. 

If Google wants me to allocate a design sprint to update italics I'd be happy to do that.

**Comment by m4rc1e** [comment]
Thank you Mr @ThomasJockin, that's clear and concise. Apologies for jumping the gun.

I will just master the 4 uprights for this release.

Cheers,
Marc

**Comment by ThomasJockin** [comment]
A pleasure! Sorry for the misunderstanding!
